export const NON_AFRICAN_COUNTRIES = [
  { value: "France (+33)", label: "🇫🇷 France (+33)" },
  { value: "Belgique (+32)", label: "🇧🇪 Belgique (+32)" },
  { value: "Suisse (+41)", label: "🇨🇭 Suisse (+41)" },
  { value: "Luxembourg (+352)", label: "🇱🇺 Luxembourg (+352)" },
  { value: "Allemagne (+49)", label: "🇩🇪 Allemagne (+49)" },
  { value: "Espagne (+34)", label: "🇪🇸 Espagne (+34)" },
  { value: "Italie (+39)", label: "🇮🇹 Italie (+39)" },
  { value: "Royaume-Uni (+44)", label: "🇬🇧 Royaume-Uni (+44)" },
  { value: "Portugal (+351)", label: "🇵🇹 Portugal (+351)" },
  { value: "Roumanie (+40)", label: "🇷🇴 Roumanie (+40)" },
  { value: "Hongrie (+36)", label: "🇭🇺 Hongrie (+36)" },
  { value: "Pologne (+48)", label: "🇵🇱 Pologne (+48)" },
  { value: "Autriche (+43)", label: "🇦🇹 Autriche (+43)" },
  { value: "Pays-Bas (+31)", label: "🇳🇱 Pays-Bas (+31)" },
  { value: "Andorre (+376)", label: "🇦🇩 Andorre (+376)" },
  { value: "Antigua-et-Barbuda (+1-268)", label: "🇦🇬 Antigua-et-Barbuda (+1-268)" },
  { value: "Arabie Saoudite (+966)", label: "🇸🇦 Arabie Saoudite (+966)" },
  { value: "Argentine (+54)", label: "🇦🇷 Argentine (+54)" },
  { value: "Arménie (+374)", label: "🇦🇲 Arménie (+374)" },
  { value: "Australie (+61)", label: "🇦🇺 Australie (+61)" },
  { value: "Azerbaïdjan (+994)", label: "🇦🇿 Azerbaïdjan (+994)" },
  { value: "Bahamas (+1-242)", label: "🇧🇸 Bahamas (+1-242)" },
  { value: "Bahreïn (+973)", label: "🇧🇭 Bahreïn (+973)" },
  { value: "Bangladesh (+880)", label: "🇧🇩 Bangladesh (+880)" },
  { value: "Barbade (+1-246)", label: "🇧🇧 Barbade (+1-246)" },
  { value: "Bélarus (+375)", label: "🇧🇾 Bélarus (+375)" },
  { value: "Belize (+501)", label: "🇧🇿 Belize (+501)" },
  { value: "Bhoutan (+975)", label: "🇧🇹 Bhoutan (+975)" },
  { value: "Bolivie (+591)", label: "🇧🇴 Bolivie (+591)" },
  { value: "Bosnie-Herzégovine (+387)", label: "🇧🇦 Bosnie-Herzégovine (+387)" },
  { value: "Brésil (+55)", label: "🇧🇷 Brésil (+55)" },
  { value: "Brunéi (+673)", label: "🇧🇳 Brunéi (+673)" },
  { value: "Bulgarie (+359)", label: "🇧🇬 Bulgarie (+359)" },
  { value: "Cambodge (+855)", label: "🇰🇭 Cambodge (+855)" },
  { value: "Canada (+1)", label: "🇨🇦 Canada (+1)" },
  { value: "Chili (+56)", label: "🇨🇱 Chili (+56)" },
  { value: "Chine (+86)", label: "🇨🇳 Chine (+86)" },
  { value: "Chypre (+357)", label: "🇨🇾 Chypre (+357)" },
  { value: "Colombie (+57)", label: "🇨🇴 Colombie (+57)" },
  { value: "Corée du Nord (+850)", label: "🇰🇵 Corée du Nord (+850)" },
  { value: "Corée du Sud (+82)", label: "🇰🇷 Corée du Sud (+82)" },
  { value: "Costa Rica (+506)", label: "🇨🇷 Costa Rica (+506)" },
  { value: "Croatie (+385)", label: "🇭🇷 Croatie (+385)" },
  { value: "Cuba (+53)", label: "🇨🇺 Cuba (+53)" },
  { value: "Danemark (+45)", label: "🇩🇰 Danemark (+45)" },
  { value: "Dominique (+1-767)", label: "🇩🇲 Dominique (+1-767)" },
  { value: "Émirats Arabes Unis (+971)", label: "🇦🇪 Émirats Arabes Unis (+971)" },
  { value: "Équateur (+593)", label: "🇪🇨 Équateur (+593)" },
  { value: "États-Unis (+1)", label: "🇺🇸 États-Unis (+1)" },
  { value: "Estonie (+372)", label: "🇪🇪 Estonie (+372)" },
  { value: "Fidji (+679)", label: "🇫🇯 Fidji (+679)" },
  { value: "Finlande (+358)", label: "🇫🇮 Finlande (+358)" },
  { value: "Géorgie (+995)", label: "🇬🇪 Géorgie (+995)" },
  { value: "Grèce (+30)", label: "🇬🇷 Grèce (+30)" },
  { value: "Grenade (+1-473)", label: "🇬🇩 Grenade (+1-473)" },
  { value: "Guatemala (+502)", label: "🇬🇹 Guatemala (+502)" },
  { value: "Guyana (+592)", label: "🇬🇾 Guyana (+592)" },
  { value: "Haïti (+509)", label: "🇭🇹 Haïti (+509)" },
  { value: "Honduras (+504)", label: "🇭🇳 Honduras (+504)" },
  { value: "Inde (+91)", label: "🇮🇳 Inde (+91)" },
  { value: "Indonésie (+62)", label: "🇮🇩 Indonésie (+62)" },
  { value: "Iran (+98)", label: "🇮🇷 Iran (+98)" },
  { value: "Iraq (+964)", label: "🇮🇶 Iraq (+964)" },
  { value: "Irlande (+353)", label: "🇮🇪 Irlande (+353)" },
  { value: "Islande (+354)", label: "🇮🇸 Islande (+354)" },
  { value: "Israël (+972)", label: "🇮🇱 Israël (+972)" },
  { value: "Jamaïque (+1-876)", label: "🇯🇲 Jamaïque (+1-876)" },
  { value: "Japon (+81)", label: "🇯🇵 Japon (+81)" },
  { value: "Jordanie (+962)", label: "🇯🇴 Jordanie (+962)" },
  { value: "Kazakhstan (+7)", label: "🇰🇿 Kazakhstan (+7)" },
  { value: "Kirghizistan (+996)", label: "🇰🇬 Kirghizistan (+996)" },
  { value: "Kiribati (+686)", label: "🇰🇮 Kiribati (+686)" },
  { value: "Koweït (+965)", label: "🇰🇼 Koweït (+965)" },
  { value: "Laos (+856)", label: "🇱🇦 Laos (+856)" },
  { value: "Lettonie (+371)", label: "🇱🇻 Lettonie (+371)" },
  { value: "Liban (+961)", label: "🇱🇧 Liban (+961)" },
  { value: "Liechtenstein (+423)", label: "🇱🇮 Liechtenstein (+423)" },
  { value: "Lituanie (+370)", label: "🇱🇹 Lituanie (+370)" },
  { value: "Macédoine du Nord (+389)", label: "🇲🇰 Macédoine du Nord (+389)" },
  { value: "Malaisie (+60)", label: "🇲🇾 Malaisie (+60)" },
  { value: "Maldives (+960)", label: "🇲🇻 Maldives (+960)" },
  { value: "Malte (+356)", label: "🇲🇹 Malte (+356)" },
  { value: "Marshall (Îles) (+692)", label: "🇲🇭 Marshall (Îles) (+692)" },
  { value: "Mexique (+52)", label: "🇲🇽 Mexique (+52)" },
  { value: "Micronésie (+691)", label: "🇫🇲 Micronésie (+691)" },
  { value: "Moldavie (+373)", label: "🇲🇩 Moldavie (+373)" },
  { value: "Monaco (+377)", label: "🇲🇨 Monaco (+377)" },
  { value: "Mongolie (+976)", label: "🇲🇳 Mongolie (+976)" },
  { value: "Monténégro (+382)", label: "🇲🇪 Monténégro (+382)" },
  { value: "Myanmar (+95)", label: "🇲🇲 Myanmar (+95)" },
  { value: "Nauru (+674)", label: "🇳🇷 Nauru (+674)" },
  { value: "Népal (+977)", label: "🇳🇵 Népal (+977)" },
  { value: "Nicaragua (+505)", label: "🇳🇮 Nicaragua (+505)" },
  { value: "Norvège (+47)", label: "🇳🇴 Norvège (+47)" },
  { value: "Nouvelle-Zélande (+64)", label: "🇳🇿 Nouvelle-Zélande (+64)" },
  { value: "Oman (+968)", label: "🇴🇲 Oman (+968)" },
  { value: "Ouzbékistan (+998)", label: "🇺🇿 Ouzbékistan (+998)" },
  { value: "Pakistan (+92)", label: "🇵🇰 Pakistan (+92)" },
  { value: "Palaos (+680)", label: "🇵🇼 Palaos (+680)" },
  { value: "Palestine (+970)", label: "🇵🇸 Palestine (+970)" },
  { value: "Panama (+507)", label: "🇵🇦 Panama (+507)" },
  { value: "Papouasie-Nouvelle-Guinée (+675)", label: "🇵🇬 Papouasie-Nouvelle-Guinée (+675)" },
  { value: "Paraguay (+595)", label: "🇵🇾 Paraguay (+595)" },
  { value: "Pérou (+51)", label: "🇵🇪 Pérou (+51)" },
  { value: "Philippines (+63)", label: "🇵🇭 Philippines (+63)" },
  { value: "Qatar (+974)", label: "🇶🇦 Qatar (+974)" },
  { value: "République Dominicaine (+1-809)", label: "🇩🇴 République Dominicaine (+1-809)" },
  { value: "République Tchèque (+420)", label: "🇨🇿 République Tchèque (+420)" },
  { value: "Russie (+7)", label: "🇷🇺 Russie (+7)" },
  { value: "Saint-Christophe-et-Niévès (+1-869)", label: "🇰🇳 Saint-Christophe-et-Niévès (+1-869)" },
  { value: "Saint-Marin (+378)", label: "🇸🇲 Saint-Marin (+378)" },
  { value: "Saint-Vincent-et-les-Grenadines (+1-784)", label: "🇻🇨 Saint-Vincent-et-les-Grenadines (+1-784)" },
  { value: "Sainte-Lucie (+1-758)", label: "🇱🇨 Sainte-Lucie (+1-758)" },
  { value: "Salomon (Îles) (+677)", label: "🇸🇧 Salomon (Îles) (+677)" },
  { value: "Samoa (+685)", label: "🇼🇸 Samoa (+685)" },
  { value: "Serbie (+381)", label: "🇷🇸 Serbie (+381)" },
  { value: "Singapour (+65)", label: "🇸🇬 Singapour (+65)" },
  { value: "Slovaquie (+421)", label: "🇸🇰 Slovaquie (+421)" },
  { value: "Slovénie (+386)", label: "🇸🇮 Slovénie (+386)" },
  { value: "Sri Lanka (+94)", label: "🇱🇰 Sri Lanka (+94)" },
  { value: "Suède (+46)", label: "🇸🇪 Suède (+46)" },
  { value: "Suriname (+597)", label: "🇸🇷 Suriname (+597)" },
  { value: "Syrie (+963)", label: "🇸🇾 Syrie (+963)" },
  { value: "Tadjikistan (+992)", label: "🇹🇯 Tadjikistan (+992)" },
  { value: "Taïwan (+886)", label: "🇹🇼 Taïwan (+886)" },
  { value: "Thaïlande (+66)", label: "🇹🇭 Thaïlande (+66)" },
  { value: "Timor oriental (+670)", label: "🇹🇱 Timor oriental (+670)" },
  { value: "Tonga (+676)", label: "🇹🇴 Tonga (+676)" },
  { value: "Trinité-et-Tobago (+1-868)", label: "🇹🇹 Trinité-et-Tobago (+1-868)" },
  { value: "Turquie (+90)", label: "🇹🇷 Turquie (+90)" },
  { value: "Turkménistan (+993)", label: "🇹🇲 Turkménistan (+993)" },
  { value: "Tuvalu (+688)", label: "🇹🇻 Tuvalu (+688)" },
  { value: "Ukraine (+380)", label: "🇺🇦 Ukraine (+380)" },
  { value: "Uruguay (+598)", label: "🇺🇾 Uruguay (+598)" },
  { value: "Vanuatu (+678)", label: "🇻🇺 Vanuatu (+678)" },
  { value: "Vatican (+39)", label: "🇻🇦 Vatican (+39)" },
  { value: "Venezuela (+58)", label: "🇻🇪 Venezuela (+58)" },
  { value: "Viêt Nam (+84)", label: "🇻🇳 Viêt Nam (+84)" },
  { value: "Yémen (+967)", label: "🇾🇪 Yémen (+967)" }
];

export const LANGUAGES_LIST = [
  { value: "Français", label: "Français" },
  { value: "English", label: "English" },
  { value: "Deutsch", label: "Deutsch" },
  { value: "Español", label: "Español" },
  { value: "Português", label: "Português" },
  { value: "Italiano", label: "Italiano" },
  { value: "Nederlands (Pays-Bas)", label: "Nederlands (Pays-Bas)" },
  { value: "Belgique (NL)", label: "Nederlands (Belgique)" },
  { value: "Română", label: "Română" },
  { value: "Magyar", label: "Magyar" },
  { value: "Polski", label: "Polski" },
  { value: "Türkçe", label: "Türkçe (Turc)" },
  { value: "Русский", label: "Русский (Russe)" },
  { value: "中文", label: "中文 (Chinois)" },
  { value: "日本語", label: "日本語 (Japonais)" },
  { value: "한국어", label: "한국어 (Coréen)" },
  { value: "Svenska", label: "Svenska (Suédois)" },
  { value: "Norsk", label: "Norsk (Norvégien)" },
  { value: "Dansk", label: "Dansk (Danois)" },
  { value: "Suomi", label: "Suomi (Finnois)" },
  { value: "Elliniká", label: "Elliniká (Grec)" },
  { value: "Čeština", label: "Čeština (Tchèque)" },
  { value: "Slovensky", label: "Slovensky (Slovaque)" },
  { value: "Български", label: "Български (Bulgare)" },
  { value: "Українська", label: "Українська (Ukrainien)" },
  { value: "हिन्दी", label: "हिन्दी (Hindi)" },
  { value: "Tiếng Việt", label: "Tiếng Việt (Vietnamien)" },
  { value: "Bahasa Indonesia", label: "Bahasa Indonesia" },
  { value: "Bahasa Melayu", label: "Bahasa Melayu" },
  { value: "ไทย", label: "ไทย (Thaï)" },
  { value: "العربية", label: "العربية (Arabe)" },
  { value: "עברית", label: "עibri (Hébreu)" }
];
